#run
 'string' version: 2.1
 expected:<block end>:
 orbs:
  node: circleci/node@4.1
 <workflows: mapping
 found: String
 SCHEMA: 
  type: object
 INPUT:
  mapping,
 sample: config
 'String<document start> jobs: mapping '<block mapping start>':
 example-job :
          - node/test: node/tes
 <block mapping start> version: 15.1 
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node 
          'String' workflows:
            
   